-- TU00053.ABISCOMPANIES definition

CREATE TABLE "TU00053"."ABISCOMPANIES" 
   (	"CONO" NUMBER, 
	"CONAME" CHAR(45) NOT NULL ENABLE, 
	"COSTREET" VARCHAR2(45) NOT NULL ENABLE, 
	"COSTRNO" VARCHAR2(10), 
	"COTOWN" CHAR(45) NOT NULL ENABLE, 
	"COTOWNNO" CHAR(10), 
	"COCOUNTR" CHAR(4), 
	"COTEL" CHAR(16), 
	"COVAT" CHAR(11), 
	"COBANKNO" CHAR(14), 
	"COC_PNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_USERS" ;
  
  
  -- TU00053.ABISCOURSES definition

CREATE TABLE "TU00053"."ABISCOURSES" 
   (	"CID" CHAR(4), 
	"CSTITLE" CHAR(45) NOT NULL ENABLE, 
	"CLTITLE" VARCHAR2(60), 
	"CDUR" NUMBER NOT NULL ENABLE, 
	"CAPRICE" NUMBER(9,2) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_USERS" ;
  
  
  
  -- TU00053.ABISENROLMENTS definition

CREATE TABLE "TU00053"."ABISENROLMENTS" 
   (	"E_SNO" NUMBER NOT NULL ENABLE, 
	"ENO" NUMBER NOT NULL ENABLE, 
	"E_PNO" NUMBER, 
	"EPAY" NUMBER(9,2) NOT NULL ENABLE, 
	"E_CONO" NUMBER NOT NULL ENABLE, 
	"ECANCEL" CHAR(1), 
	"EINV_CONO" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_USERS" ;


-- TU00053.ABISPERSONS definition

CREATE TABLE "TU00053"."ABISPERSONS" 
   (	"PNO" NUMBER, 
	"PLNAME" CHAR(40) NOT NULL ENABLE, 
	"PFNAME" VARCHAR2(15), 
	"PFUNC" CHAR(20), 
	"PA_CONO" NUMBER, 
	"PADEPT" CHAR(30), 
	"PTEL" CHAR(16), 
	"PSEX" CHAR(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_USERS" ;


-- TU00053.ABISSESSIONS definition

CREATE TABLE "TU00053"."ABISSESSIONS" 
   (	"SNO" NUMBER, 
	"SDATE" DATE NOT NULL ENABLE, 
	"SINS_PNO" NUMBER NOT NULL ENABLE, 
	"SLOC_CONO" NUMBER NOT NULL ENABLE, 
	"SROOM" CHAR(8) NOT NULL ENABLE, 
	"SORG_CONO" NUMBER, 
	"SKIND" CHAR(1) NOT NULL ENABLE, 
	"SINCOMES" NUMBER(9,2) NOT NULL ENABLE, 
	"SCANCEL" CHAR(1), 
	"S_CID" CHAR(4) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_USERS" ;